version: '2'

services:
  producer:
    build:
      context: $PWD
      dockerfile: deploy/local/Dockerfile
    container_name: producer
    command: ./docker-entrypoint.sh --mode=producer --url=https://status.dev.azure.com/_apis/status/health --seconds=30 --pattern="critical"
    depends_on:
      - consumer
    environment:
      - KAFKA_TOPIC_SUCCESS
      - KAFKA_TOPIC_FAILURE
      - KAFKA_BOOTSTRAP_SERVERS
      - KAFKA_CAFILE
      - KAFKA_CERTFILE
      - KAFKA_KEYILE
      - KAFKA_CONSUMER_GROUP
      - LOGURU_LEVEL
    volumes:
      - '$PWD/certificates:/var/certs'
  consumer:
    build:
      context: $PWD
      dockerfile: deploy/local/Dockerfile
    container_name: consumer
    command: ./docker-entrypoint.sh --mode=consumer --no-autocommit
    environment:
      - KAFKA_TOPIC_SUCCESS
      - KAFKA_TOPIC_FAILURE
      - KAFKA_BOOTSTRAP_SERVERS
      - KAFKA_CAFILE
      - KAFKA_CERTFILE
      - KAFKA_KEYILE
      - POSTGRES_DSN
      - LOGURU_LEVEL
    volumes:
      - '$PWD/certificates:/var/certs'
